// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WorkCale.Infrastructure.Persistence;

#nullable disable

namespace WorkCale.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314000000_AddCategoryDefaultTimes")]
    partial class AddCategoryDefaultTimes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
